name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Docker Build & Push
        run: |
          docker build -t ${DOCKERHUB_USERNAME}/zyra-moments-client-service .
          docker push ${DOCKERHUB_USERNAME}/zyra-moments-client-service

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Setting up Docker Hub login on EC2..."
            export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
            export DOCKERHUB_TOKEN="${{ secrets.DOCKERHUB_TOKEN }}"

            # Now Docker login with the token on EC2
            echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin || { echo "Docker login failed"; exit 1; }

            # Docker compose commands
            docker compose down || { echo "Docker compose down failed"; exit 1; }
            docker compose pull || { echo "Docker compose pull failed"; exit 1; }
            docker compose up -d || { echo "Docker compose up failed"; exit 1; }
